execution_client_name: openethereum
execution_image_name: openethereum/openethereum
execution_endpoint: http://127.0.0.1:{{execution_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{execution_engine_snoop_port}} http://127.0.0.1:{{execution_engine_port}}"

execution_github_external_user_pubkeys: []
execution_miner_keystore_dir: "{{testnet_dir}}/miner_keystores/{{beacon_network_name}}"

execution_memory: 5000M
execution_kernel_memory: 5500M

# websocket with upgrade
eth1endpoint_ws: http://127.0.0.1:8546

# Must not use paths in root dir, or openethereum user doesn't have permissions
execution_volumes:
  - "{{execution_node_dir}}:/home/openethereum/execution"
  - "{{testnet_dir}}:/home/openethereum/networkdata"

execution_start_args: >
  --chain /home/openethereum/networkdata/chainspec.json
  --base-path /home/openethereum/execution
  --no-warp
  --mode=active
  --tracing=on
  {% if mining_keyi is defined %}
  --force-sealing
  --engine-signer={{mining_addresses[mining_keyi]}}
  --keys-path=/home/openethereum/networkdata/miner_keystores
  --password=/home/openethereum/networkdata/{{keystore_password_filename}}
  --unlock={{mining_addresses[mining_keyi]}}
  {% endif %}
  --identity {{inventory_hostname}}
  --jsonrpc-port {{execution_rpc_port}}
  --jsonrpc-interface 0.0.0.0
  --jsonrpc-apis web3,eth,net,parity
  --jsonrpc-hosts all
  --jsonrpc-cors all
  {% if (bootnode_enodes is defined) and bootnode_enodes %}
  --bootnodes {{bootnode_enodes | join(',')}}
  {% endif %}
  --port {{execution_p2p_port}}
  --ws-interface 0.0.0.0
  --ws-port 8546
  --ws-hosts all
  --ws-max-connections 1000
  --metrics
  --metrics-interface all
  --metrics-port {{execution_metrics_port}}

execution_user_id: "1000:1000"
execution_keystore_attr: "u+w,g+w,o+w"
