---
- name: Configure Logging Agent
  hosts: hetzner
  gather_facts: false
  vars_prompt:
    - name: user
      prompt: Enter the Opensearch User
    - name: password
      prompt: Enter the Opensearch Password
  serial: 20  
  tasks:
    - name: Add listener to get logs send locally
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        marker: "# ANSIBLE MANAGED BLOCK - forwarding port {mark}"
        state: present
        block: |2
           <source>
             @type forward
             port 24224
             bind 0.0.0.0
           </source>

    - name: Add systemd source
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        insertafter: EOF
        marker: "# ANSIBLE MANAGED BLOCK - systemd source {mark}"
        state: present
        block: |2
          <source>
            @type systemd
            tag es.systemd
            path /var/log/journal
            read_from_head true
            <storage>
                @type local
                path /var/tmp/td-agent/tail/systemd-cursor.json
            </storage>

            <entry>
              fields_strip_underscores true
              fields_lowercase true
            </entry> 
          </source>

    - name: Create tail position file consul
      file:
        path: /var/tmp/td-agent/tail/systemd-cursor.json
        state: touch
        owner: td-agent
        group: td-agent
      become: yes

    - name: Add syslog logger
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        insertafter: EOF
        marker: "# ANSIBLE MANAGED BLOCK - syslog logger {mark}"
        state: present
        block: |2
          <source>
            @type tail
            format none
            path /var/log/syslog
            pos_file /var/tmp/td-agent/tail/syslog-cursor.pos
            tag es.syslog
            path_key tailed_path
            <parse>
              @type syslog
            </parse>
          </source>

    - name: Create tail position file
      file:
        path: /var/tmp/td-agent/tail/syslog-cursor.pos
        state: touch
        owner: td-agent
        group: td-agent
      become: yes

    - name: Creates directory
      file:
        path: /var/log/elasticsearch_logs_buffer/
        state: directory
        owner: td-agent
        group: td-agent
      become: yes

    - name: Install td agent grafana gem
      shell: td-agent-gem install fluent-plugin-elasticsearch
      become: yes

    # Elasticsearch
    - name: Add elasticsearch output 
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        state: present
        block: |2
              <match es.**>
                    # https://docs.fluentd.org/output/elasticsearch#user-password-optional 
                    @type elasticsearch
                    @log_level debug
                    host search-gnosis-merge-nev36iek55lsofh2hz3evzkolq.eu-central-1.es.amazonaws.com
                    port 443
                    scheme https
                    user {{ user }}
                    password {{ password }}
                    index_name fluentd_merge
                    type_name fluentd_merge
                    logstash_format false
                    include_tag_key false

                    # Set the chunk limit the same as for fluentd-gcp.
                    buffer_chunk_limit 200M
                    # Cap buffer memory usage to 2MiB/chunk * 32 chunks = 64 MiB
                    buffer_queue_limit 32
                    flush_interval 10s
                    # Never wait longer than 5 minutes between retries.
                    max_retry_wait 30
                    # Disable the limit on the number of retries (retry forever).
                    disable_retry_limit
                    # Use multiple threads for processing.
                    num_threads 8
                    # AWS ElasticSearch does not properly support reload connections
                    reload_connections false
                    # Capture the 400 error reasons without all the other debug logs
                    log_es_400_reason false
              </match>



