---
- name: Configure Logging Agent
  hosts: all
  gather_facts: false
  vars_prompt:
    - name: user
      prompt: Enter the Opensearch User
    - name: password
      prompt: Enter the Opensearch Password
    - name: host 
      prompt: Enter the fluentd aggregator host
  serial: 20  
  tasks:
    - name: Add listener to get logs send locally
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        marker: "# ANSIBLE MANAGED BLOCK - forwarding port {mark}"
        state: present
        block: |2
           <source>
             @type forward
             port 24224
             bind 0.0.0.0
           </source>

    - name: Install td agent fluentd prometheus gem
      shell: td-agent-gem install fluent-plugin-prometheus
      become: yes

    - name: Add metrics for fluentd
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        marker: "# ANSIBLE MANAGED BLOCK -  metrics exposure {mark}"
        state: present
        block: |2
            <source> 
              @type prometheus 
              <labels> 
                hostname "#{Socket.gethostname}" 
              </labels> 
            </source> 
            <source> 
              @type prometheus
              bind 0.0.0.0 
              port 24231 
              metrics_path /metrics
            </source> 
          
    - name: Add transformation to logs 
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        marker: "# ANSIBLE MANAGED BLOCK -  log adaption {mark}"
        state: present
        block: |2
            <filter es.**> 
              @type record_transformer
              enable_ruby
              <record> 
                fluentd_worker "#{worker_id}"
                hostname_agent_machine "#{Socket.gethostname}" 
                ip_address_agent_machine "#{Socket.ip_address_list[1].ip_address}"
              </record> 
            </filter> 
      
    - name: Add systemd source
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        insertafter: EOF
        marker: "# ANSIBLE MANAGED BLOCK - systemd source {mark}"
        state: present
        block: |2
          <source>
            @type systemd
            tag es.systemd
            path /var/log/journal
            read_from_head true
            <storage>
                @type local
                path /var/tmp/td-agent/tail/systemd-cursor.json
            </storage>

            <entry>
              fields_strip_underscores true
              fields_lowercase true
            </entry> 
          </source>

    - name: Create tail position file consul
      file:
        path: /var/tmp/td-agent/tail/systemd-cursor.json
        state: touch
        owner: td-agent
        group: td-agent
      become: yes

    - name: Add syslog logger
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        insertafter: EOF
        marker: "# ANSIBLE MANAGED BLOCK - syslog logger {mark}"
        state: present
        block: |2
          <source>
            @type tail
            path /var/log/syslog
            pos_file /var/tmp/td-agent/tail/syslog-cursor.pos
            tag es.syslog
            path_key tailed_path
            <parse>
              @type syslog
            </parse>
          </source>

    - name: Create tail position file
      file:
        path: /var/tmp/td-agent/tail/syslog-cursor.pos
        state: touch
        owner: td-agent
        group: td-agent
      become: yes

    - name: Creates directory
      file:
        path: /var/log/elasticsearch_logs_buffer/
        state: directory
        owner: td-agent
        group: td-agent
      become: yes

    - name: Install td agent grafana gem
      shell: td-agent-gem install fluent-plugin-elasticsearch
      become: yes

    - name: Install td agent fluentd plugin 
      shell: td-agent-gem install fluent-plugin-systemd -v 1.0.3
      become: yes

    # Elasticsearch
    - name: Add elasticsearch output 
      become: yes
      blockinfile:
        path: "/etc/td-agent/td-agent.conf"
        state: present
        insertafter: EOF
        marker: "# ANSIBLE MANAGED BLOCK - elasticsearch {mark}"
        block: |2
              <match es.**>
                    # https://docs.fluentd.org/output/elasticsearch#user-password-optional 
                    @type elasticsearch
                    @log_level debug
                    host {{ host }}
                    port 443
                    scheme https
                    user {{ user }}
                    password {{ password }}
                    index_name fluentd_merge
                    type_name fluentd_merge
                    logstash_format false
                    include_tag_key true
                    tag_key _key
                    include_timestamp true

                    # Set the chunk limit the same as for fluentd-gcp.
                    buffer_chunk_limit 200M
                    # Cap buffer memory usage to 2MiB/chunk * 32 chunks = 64 MiB
                    buffer_queue_limit 32
                    flush_interval 10s
                    # Never wait longer than 5 minutes between retries.
                    max_retry_wait 30
                    # Disable the limit on the number of retries (retry forever).
                    disable_retry_limit
                    # Use multiple threads for processing.
                    num_threads 8
                    # AWS ElasticSearch does not properly support reload connections
                    reload_connections false
                    # Capture the 400 error reasons without all the other debug logs
                    log_es_400_reason false
              </match>



