- name: cloudalchemy.node_exporter
  version: "2.0.0"
- name: cloudalchemy.prometheus
  version: "2.16.2"
- name: gantsign.oh-my-zsh
  version: "2.4.0"
- name: geerlingguy.docker
  version: "4.2.3"
- name: geerlingguy.pip
  version: "2.2.0"
- name: geerlingguy.firewall
  version: "2.5.0"
- name: robertdebock.bootstrap
  version: "6.0.3"
- name: robertdebock.update_package_cache
  version: "2.1.2"
- name: robertdebock.fail2ban
  version: "4.2.3"
- name: ome.cadvisor
  version: "0.4.0"
- name: patrickjahns.promtail
  version: "1.17.0"
