eth1_client_name: nethermind
eth1_image_name: nethermindeth/nethermind:gnosis
execution_endpoint: http://127.0.0.1:{{eth1_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{eth1_engine_snoop_port}} http://127.0.0.1:{{eth1_engine_port}}"

home_dir: "/home/{{ansible_user}}"

eth1_github_external_user_pubkeys:
  - MarekM25
  - avalonche
  - DockBoss
  - LukaszRozmej
  - marcindsobczak
  - jmederosalvarado

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# websocket with upgrade
eth1endpoint_ws: http://127.0.0.1:8546

eth1_volumes:
  - "{{execution_node_dir}}:/execution"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

eth1_start_args: >
  --config=/networkdata/nethermind_config.cfg
  --datadir="/execution"
  --Init.ChainSpecPath="/networkdata/nethermind_genesis.json"
  --Init.WebSocketsEnabled=true
  --JsonRpc.EnabledModules="net,eth,consensus,subscribe,web3,admin,txpool,debug"
  --JsonRpc.Host=0.0.0.0
  --JsonRpc.Port={{eth1_rpc_port}}
  --JsonRpc.EnginePort={{eth1_engine_port}}
  --JsonRpc.WebSocketsPort={{eth1_ws_rpc_port}}
  --JsonRpc.JwtSecretFile=/jwtsecret
  --JsonRpc.AdditionalRpcUrls="http://localhost:{{eth1_engine_port_no_auth}}|http;ws|net;eth;subscribe;engine;web3;client,debug|no-auth"
  --Network.DiscoveryPort=30303
  --Network.P2PPort=30303
  --Merge.Enabled=true
  --Merge.TerminalTotalDifficulty={{terminal_total_difficulty}}
  --Init.DiagnosticMode="None"
  --EthStats.Enabled=false
  --Metrics.ExposePort={{eth1_metrics_port}}
  --Metrics.Enabled=true
  --AuRaMerge.Enabled=true
  --Aura.TxPriorityContractAddress=0x4100000000000000000000000000000000000000
  --Aura.ForceSealing=true
  --Seq.MinLevel="Info"
  --Seq.ServerUrl="https://seq.nethermind.io/"
  --Seq.ApiKey="{{nethermind_seq_api_key}}"
  {% if (use_snap_sync is defined) and use_snap_sync %}
  --Sync.SnapSync=true
  --Sync.FastSync=false
  {% else %}
  --Sync.SnapSync=false
  --Sync.FastSync=true
  {% endif %}

# run as root, the nethermind image doesn't handle running regular user well
eth1_user_id: "0:0"
