execution_client_name: erigon
execution_image_name: thorax/erigon:v2022.05.08
execution_endpoint: http://127.0.0.1:{{execution_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{execution_engine_snoop_port}} http://127.0.0.1:{{execution_engine_port}}"

home_dir: "/home/{{ansible_user}}"

execution_github_external_user_pubkeys:
  - Giulio2002
  - yperbasis

# bare websocket
eth1endpoint_ws: ws://127.0.0.1:8546

execution_volumes:
  - "{{execution_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

geth_init_args: >
  erigon --datadir=/eth1data init /networkdata/genesis.json

execution_start_args: >
  erigon --datadir=/eth1data
  --networkid={{chainID}}
  --http --http.api "admin,engine,net,eth"
  --http.port {{execution_rpc_port}}
  --http.addr 0.0.0.0
  --http.corsdomain "*"
  --ws
  --engine.port={{execution_engine_port}}
  --engine.addr=0.0.0.0
  --authrpc.jwtsecret=/jwtsecret
  --nat extip:{{ansible_host}}
  --allow-insecure-unlock
  --prune=htrc
  --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port={{execution_metrics_port}}
  --override.terminaltotaldifficulty={{terminal_total_difficulty}}
  --ethstats={{inventory_hostname}}:{{ethstats_password}}@{{ethstats_host}}
  {% if (execution_bootnode_enode is defined) and execution_bootnode_enode %}
  --bootnodes "{{ execution_bootnode_enode | join(',') }}"
  {% endif %}

execution_user_id: "1000:1000"
