execution_client_name: besu
execution_image_name: hyperledger/besu:22.4.3-SNAPSHOT-openjdk-11-debug
execution_endpoint: http://127.0.0.1:{{execution_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{execution_engine_snoop_port}} http://127.0.0.1:{{execution_engine_port}}"

home_dir: "/home/{{ansible_user}}"

execution_memory: 5000M
execution_kernel_memory: 5500M

execution_github_external_user_pubkeys:
  - garyschulte
  - jflo
  - fab-10
  - matkt
  - gezero

# websocket with /ws suffix
eth1endpoint_ws: ws://127.0.0.1:8546/ws

execution_volumes:
  - "{{execution_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

execution_env:
  JDWP_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  NATIVE_MEMORY_OPTS: "-XX:NativeMemoryTracking=detail -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics"

execution_start_args: >
  --data-path="/eth1data/data"
  --genesis-file="/networkdata/besu_genesis.json"
  --network-id={{chainID}}
  --required-block=14699639=0x33c08518915716224cb2ad6364fc49cc0f941e33e233ae629a8baff5956c57ba
  --max-peers=100
  --rpc-http-enabled=true --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE
  --rpc-http-host=0.0.0.0
  --rpc-http-port={{execution_rpc_port}}
  --engine-rpc-enabled=true
  --engine-rpc-port={{execution_engine_port}}
  --engine-host-allowlist="*"
  --rpc-http-cors-origins="*"
  --rpc-ws-enabled=true --rpc-ws-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE
  --rpc-ws-host=0.0.0.0
  --host-allowlist="*"
  --metrics-enabled
  --metrics-host=0.0.0.0
  --metrics-port={{execution_metrics_port}}
  --p2p-enabled=true
  --miner-coinbase="{{fee_recipient}}"
  --p2p-host={{ansible_host}}
  --sync-mode=X_SNAP
  --data-storage-format="BONSAI"
  --engine-jwt-enabled
  --engine-jwt-secret=/jwtsecret
  --ethstats={{inventory_hostname}}:{{ethstats_password}}@{{ethstats_host}}
  {% if (execution_bootnode_enode is defined) and bootnode_enrs %}
  --bootnodes="{{ execution_bootnode_enode | join(',') }}"
  {% endif %}

execution_user_id: "1000:1000"
