execution_client_name: openethereum
execution_image_name: openethereum/openethereum
execution_endpoint: http://127.0.0.1:{{execution_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{execution_engine_snoop_port}} http://127.0.0.1:{{execution_engine_port}}"

home_dir: "/home/{{ansible_user}}"

execution_github_external_user_pubkeys: []

execution_memory: 5000M
execution_kernel_memory: 5500M

# websocket with upgrade
eth1endpoint_ws: http://127.0.0.1:8546

execution_volumes:
  - "{{execution_node_dir}}:/home/openethereum/execution"

execution_start_args: >
  --chain xdai
  --base-path /home/openethereum/execution
  --jsonrpc-port {{execution_rpc_port}}
  --jsonrpc-interface 0.0.0.0
  --jsonrpc-apis web3,eth,net,parity
  --jsonrpc-hosts all
  --jsonrpc-cors all
  --port {{execution_p2p_port}}
  --ws-interface 0.0.0.0
  --ws-port 8546
  --ws-hosts all
  --ws-max-connections 1000
  --metrics
  --metrics-interface all
  --metrics-port {{execution_metrics_port}}

execution_user_id: "1000:1000"
