- name: Generate validator keys
  hosts: validator
  gather_facts: false
  become: true
  vars:
    output_keys_dirpath: /tmp/generated_keys/validator
    output_keys_dirpath_cont: /validator_prep/validator
    output_keys_dirpath_volume: /tmp/generated_keys:/validator_prep
  tasks:
    - name: Parse indexes range
      set_fact:
        from_index: "{{ indexes.split('..')[0] | int }}"
        to_index: "{{ indexes.split('..')[1] | int }}"

    - name: Clear directory
      become: true
      shell: rm -rf {{output_keys_dirpath}}

    - name: Creates validator dir
      file:
        path: "{{validator_node_dir}}"
        state: directory

    - name: Generate keys
      # Do not --rm to allow the auditing of params
      shell: >
        docker run --entrypoint=eth2-val-tools --name eth2_keys_generator \
        -v {{output_keys_dirpath_volume}} \
        skylenet/ethereum-genesis-generator keystores \
        --insecure \
        --prysm-pass="prysm" \
        --out-loc="{{output_keys_dirpath_cont}}" \
        --source-max={{to_index}} \
        --source-min={{from_index}} \
        --source-mnemonic="{{mnemonic}}"
    # Grab the right keys for each eth2 client
    - name: Copy keys for lighthouse
      when: eth2_client_name == 'lighthouse'
      shell: |
        cp -r "{{output_keys_dirpath}}/keys" "{{validator_node_dir}}/validators"
        cp -r "{{output_keys_dirpath}}/secrets" "{{validator_node_dir}}/secrets"
        chown -R {{bootstrap_user}}:{{bootstrap_user}} {{validator_node_dir}}
    - name: Copy keys for teku
      when: eth2_client_name == 'teku'
      shell: |
        cp -r "{{output_keys_dirpath}}/teku-keys" "{{validator_node_dir}}/keys"
        cp -r "{{output_keys_dirpath}}/teku-secrets" "{{validator_node_dir}}/secrets"
        chown -R {{bootstrap_user}}:{{bootstrap_user}} {{validator_node_dir}}
    - name: Create folders for prysm
      when: eth2_client_name == 'prysm'
      shell: |
        mkdir -p "{{validator_node_dir}}/wallet/direct/accounts"
        echo "prysm" > "{{validator_node_dir}}/wallet_pass.txt"
        cp -r "{{output_keys_dirpath}}/prysm/direct/accounts/all-accounts.keystore.json" "{{validator_node_dir}}/wallet/direct/accounts/all-accounts.keystore.json"
        cp -r "{{output_keys_dirpath}}/prysm/keymanageropts.json" "{{validator_node_dir}}/wallet/direct/keymanageropts.json"
        chown -R {{bootstrap_user}}:{{bootstrap_user}} {{validator_node_dir}}
    - name: Copy keys for nimbus
      when: eth2_client_name == 'nimbus'
      shell: |
        cp -r "{{output_keys_dirpath}}/nimbus-keys" "{{validator_node_dir}}/keys"
        cp -r "{{output_keys_dirpath}}/secrets" "{{validator_node_dir}}/secrets"
        chown -R {{bootstrap_user}}:{{bootstrap_user}} {{validator_node_dir}}
    - name: Copy keys for lodestar
      when: eth2_client_name == 'lodestar'
      shell: |
        cp -r "{{output_keys_dirpath}}/keys" "{{validator_node_dir}}/keystores"
        cp -r "{{output_keys_dirpath}}/secrets" "{{validator_node_dir}}/secrets"
    - name: Modify permissions to match user-group inside docker image
      shell: chown -R "{{validator_user_id}}" "{{validator_node_dir}}"
      become: true
