- name: Init explorer sql tables
  hosts: explorer_beacon
  gather_facts: false
  tasks:
    - name: Sleep for 15 seconds and continue with play
      wait_for:
        timeout: 15
      delegate_to: localhost
    - name: Run psql table creation
      docker_container:
        name: "postgres_tmp"
        state: started
        image: "{{ explorer_beacon_postgres_image_name }}"
        pull: true
        restart_policy: no
        auto_remove: false
        detach: no
        network_mode: host
        volumes: "{{ explorer_beacon_postgres_init_volumes }}"
        command: "{{ explorer_beacon_postgres_init_args }}"
        env:
          PGPASSWORD: "{{ explorer_beacon_postgres_password }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
