---
- name: Start node exporter and prometheus
  hosts: beacon, validator, execution
  gather_facts: true
  vars: 
  # enter pushgateway config if needed
    prometheus_config_file: "prometheus/prometheus.yml.j2"
    push_url: "https://themerge-monitoring.gnosischainscan.com/pushgateway/metrics/job/node_metrics/instance/gbc-merge"
    push_metrics_enabled: true
    remote_write_auth: true
    eth2_validator_metrics_enabled: true
    eth_metrics_exporter_enabled: true
    eth_metrics_exporter_name: "metrics-exporter"
    eth_metrics_exporter_image: samcm/ethereum-metrics-exporter:0.11.0
    cadvisor_enabled: true 
    cadvisor_port: 8085
    eth2_network_name: "merge"
    remote_write_username: "prometheus"
    remote_write_password: "neboWcmRwkbuk60y"
    eth_metrics_exporter_port: 9100
  roles:
    #- cloudalchemy.node_exporter
    - cloudalchemy.prometheus
    - role: ome.cadvisor
      when: cadvisor_enabled|bool == true
    - role: patrickjahns.promtail
      when: promtail_enabled|bool == true
      vars:
        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: varlogs
                  __path__: /var/log/*log

  tasks:
    - name: Start exporter container
      when:
        - eth_metrics_exporter_enabled | bool
        - eth2_client_name is defined
        - eth1_client_name is defined
      docker_container:
        name: "{{ eth_metrics_exporter_name }}"
        state: started
        image: "{{ eth_metrics_exporter_image }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ eth1_require_restart | default(false) }}"
        command: "--consensus-url={{beacon_api_endpoint}} --execution-url={{eth1endpoint}} --metrics-port={{eth_metrics_exporter_port}}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
