- name: Start node exporter and prometheus
  hosts: beacon, validator, execution
  gather_facts: true
  pre_tasks:
    - name: Download prometheus binaries from host
      when: prometheus_binary_url is defined
      block:
        - name: Download prometheus_binaries
          become: true
          get_url:
            url: "{{prometheus_binary_url}}/{{item}}"
            dest: "/usr/local/bin/{{item}}"
            mode: "755"
          with_items:
            - prometheus
            - promtool

  roles:
    - cloudalchemy.node_exporter
    - cloudalchemy.prometheus
    - role: ome.cadvisor
      when: cadvisor_enabled|bool == true

  tasks:
    - name: Start exporter container
      when:
        - eth_metrics_exporter_enabled | bool
        - eth2_client_name is defined
        - eth1_client_name is defined
        - eth2_client_name != "lodestar"
      docker_container:
        name: "{{ eth_metrics_exporter_name }}"
        state: started
        image: "{{ eth_metrics_exporter_image }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ eth1_require_restart | default(false) }}"
        command: "--consensus-url={{beacon_api_endpoint}} --execution-url={{eth1endpoint}} --metrics-port={{eth_metrics_exporter_port}}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
