- name: Start node exporter and prometheus
  hosts: beacon, validator, execution
  gather_facts: true
  pre_tasks:
    - name: Download prometheus binaries
      when: prometheus_binary_url is defined
      get_url:
        url: "{{prometheus_binary_url}}/{{item}}"
        dest: "/usr/local/bin/{{item}}"
        mode: 755
      become: true
      with_items:
        - promtool
        - prometheus

  roles:
    - cloudalchemy.node_exporter
    - cloudalchemy.prometheus
    - role: ome.cadvisor
      when: cadvisor_enabled|bool == true
    - role: patrickjahns.promtail
      when: promtail_enabled|bool == true
      vars:
        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: varlogs
                  __path__: /var/log/*log

  tasks:
    - name: Start exporter container
      when:
        - eth_metrics_exporter_enabled | bool
        - beacon_client_name is defined
        - execution_client_name is defined
        - beacon_client_name != "lodestar"
      docker_container:
        name: "{{ eth_metrics_exporter_name }}"
        state: started
        image: "{{ eth_metrics_exporter_image }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ execution_require_restart | default(false) }}"
        command: "--consensus-url={{beacon_api_endpoint}} --execution-url={{eth1endpoint}} --metrics-port={{eth_metrics_exporter_port}}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
