- name: Start execution node
  hosts: execution
  gather_facts: false
  serial: 20
  tasks:
    - name: Start execution node container
      docker_container:
        name: "{{ execution_container_name }}"
        state: started
        image: "{{ eth1_image_name }}"
        pull: true
        restart_policy: unless-stopped
        log_driver: {{ docker_log_driver | default('json-file') }}
        network_mode: host
        restart: "{{ eth1_require_restart | default(false) }}"
        volumes: "{{eth1_volumes}}"
        command: "{{ eth1_start_args }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        env: "{{ eth1_env | default({}) }}"
