- name: Start explorer
  hosts: explorer
  gather_facts: false
  serial: 20
  tasks:
    - name: Start Eth2 explorer
      docker_container:
        name: "{{ beacon_explorer_container_name }}"
        state: started
        image: "{{ beacon_explorer_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ explorer_require_restart | default(false) }}"
        memory: "{{explorer_memory}}"
        command: "{{ beacon_explorer_start_args }}"
        volumes: "{{beacon_explorer_volumes}}"
