- name: Start beacon node
  hosts: beacon
  gather_facts: false
  serial: 20
  tasks:
    - name: Creates beacon dir
      file:
        path: "{{beacon_node_dir}}"
        state: directory
    # - name: Modify permissions to match user-group inside docker image
    #   shell: chown -R "{{ beacon_user_id }}" "{{ beacon_node_dir }}"
    #   become: true
    - name: Start Eth2 beacon node container
      docker_container:
        name: "{{ beacon_container_name }}"
        state: started
        image: "{{ beacon_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ beacon_require_restart | default(false) }}"
        volumes: "{{beacon_volumes}}"
        command: "{{ beacon_start_args }}"
        env: "{{ beacon_env | default({}) }}"
        user: "{{ beacon_user_id }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
