- name: Start explorer docker net
  hosts: explorer_beacon, explorer_execution
  gather_facts: true
  tasks:
    # postgres on 172.1.1.100
    # explorer on 172.1.1.101
    # beacon   on 172.1.1.102
    # eth1     on 172.1.1.103   # removed for Altair purposes, used in Merge
    # explorerstats on 172.1.1.104
    - name: Create explorer net
      docker_network:
        name: "{{explorer_docker_network_name}}"
        ipam_config:
          - subnet: 172.1.1.0/24
            gateway: 172.1.1.1
            iprange: 172.1.1.0/24
