- name: Start bootnodes
  hosts: bootnode
  gather_facts: true
  tasks:
    - name: Start Eth2 bootnode
      docker_container:
        name: "{{ bootnode_container_name }}"
        state: started
        image: "{{ bootnode_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ bootnode_require_restart | default(false) }}"
        memory: "{{bootnode_memory}}"
        command: "{{ bootnode_start_args }}"
        volumes: "{{ bootnode_volumes }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
