- name: Start explorer postgres db
  hosts: explorer
  gather_facts: false
  tasks:
    - name: Create postgres storage dir
      file:
        path: "{{explorer_postgres_host_dir}}"
        state: directory

    - name: Start Postgres database
      docker_container:
        name: "{{ explorer_postgres_container_name }}"
        state: started
        image: "{{ explorer_postgres_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        expose:
          - "{{explorer_postgres_port}}"
        restart: "{{ explorer_postgres_require_restart | default(false) }}"
        memory: "{{explorer_postgres_memory}}"
        command: "{{ explorer_postgres_start_args }}"
        volumes: "{{explorer_postgres_volumes}}"
        env:
          POSTGRES_PASSWORD: "{{ explorer_postgres_password }}"
          POSTGRES_USER: postgres
          POSTGRES_PORT: "{{explorer_postgres_port}}"
          POSTGRES_DB: db
          PGDATA: "/postgresql/data"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
