- name: Start explorer statistics
  hosts: explorer
  gather_facts: false
  serial: 20
  tasks:
    - name: Start Eth2 explorer statistics
      docker_container:
        name: "{{ explorer_stats_container_name }}"
        state: started
        image: "{{ beacon_explorer_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ explorer_stats_require_restart | default(false) }}"
        command: "{{ explorer_stats_start_args }}"
        volumes: "{{explorer_stats_volumes}}"
