- name: Upload beacon explorer data
  hosts: explorer_beacon
  gather_facts: false
  tasks:
    - name: Creates explorer dir
      file:
        path: "{{explorer_beacon_host_dir}}"
        state: directory

    - name: Load config
      delegate_to: localhost
      set_fact:
        beacon_config: "{{ lookup('file', local_beacon_config_filepath) | from_yaml }}"

    - name: Template config
      template:
        src: "./templates/beaconchain_explorer/config.yaml"
        dest: "{{explorer_beacon_host_dir}}/config.yaml"
    - name: Copy imprint.html
      copy:
        src: "./templates/beaconchain_explorer/imprint.html"
        dest: "{{explorer_beacon_host_dir}}/imprint.html"
    - name: Copy tables.sql
      copy:
        src: "./templates/beaconchain_explorer/tables.sql"
        dest: "{{explorer_beacon_host_dir}}/tables.sql"
    - name: Copy eth2 config
      copy:
        src: "{{local_beacon_config_filepath}}"
        dest: "{{explorer_beacon_host_dir}}/beacon_config.yaml"
