- name: Upload network data
  hosts: beacon, validator, execution
  gather_facts: true
  tasks:
    - name: Archive custom_config_data dir to prepare for upload
      archive:
        path: "{{local_custom_config_data_host_dir}}/*"
        dest: "{{local_custom_config_data_host_archive}}"
      delegate_to: localhost
      run_once: true
    - name: Creates tmp testnet dir
      file:
        path: /tmp/testnet_dir
        state: directory
    - name: Creates testnet dir
      file:
        path: "{{testnet_dir}}"
        state: directory
    - name: Upload config data to remote
      unarchive:
        src: "{{ local_custom_config_data_host_archive }}"
        dest: /tmp/testnet_dir
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Copy tmp files to testnet dir
      delegate_to: "{{ inventory_hostname }}"
      become: true
      shell: cp -r /tmp/testnet_dir/* "{{testnet_dir}}"
    - name: Modify permissions to match user-group inside docker image
      shell: chown -R 777 "{{ testnet_dir }}"
      become: true

    - name: Copy keystore password
      when: "inventory_hostname in groups['execution']"
      become: true
      copy:
        dest: "{{testnet_dir}}/{{keystore_password_filename}}"
        content: "{{keystores_password}}"
