execution_client_name: nethermind
execution_image_name: nethermindeth/nethermind:gnosis
execution_endpoint: http://127.0.0.1:{{execution_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{execution_engine_snoop_port}} http://127.0.0.1:{{execution_engine_port}}"

home_dir: "/home/{{ansible_user}}"

execution_github_external_user_pubkeys:
  - MarekM25
  - avalonche
  - DockBoss
  - LukaszRozmej
  - marcindsobczak
  - jmederosalvarado
  - cbermudez97

execution_memory: 5000M
execution_kernel_memory: 5500M

# websocket with upgrade
eth1endpoint_ws: http://127.0.0.1:8546

execution_volumes:
  - "{{execution_node_dir}}:/execution"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

execution_start_args: >
  --config=/networkdata/nethermind_config.cfg
  --datadir="/execution"
  --Init.ChainSpecPath="/networkdata/nethermind_genesis.json"
  --Init.WebSocketsEnabled=true
  --JsonRpc.Enabled=true
  {% if (is_execution_explorer is defined) and is_execution_explorer %}
  --JsonRpc.EnabledModules="net,eth,consensus,subscribe,web3,admin,trace,txpool"
  {% else %}
  --JsonRpc.EnabledModules="net,eth,consensus,subscribe,web3,admin"
  {% endif %}
  --JsonRpc.Port={{execution_rpc_port}}
  --JsonRpc.WebSocketsPort={{execution_ws_rpc_port}}
  --JsonRpc.Host=0.0.0.0
  --Network.DiscoveryPort=30303
  --Network.P2PPort=30303
  --Merge.Enabled=true
  --Merge.TerminalTotalDifficulty={{terminal_total_difficulty}}
  --Init.DiagnosticMode="None"
  --JsonRpc.JwtSecretFile=/jwtsecret
  --JsonRpc.AdditionalRpcUrls="http://localhost:{{execution_engine_port_no_auth}}|http;ws|net;eth;subscribe;engine;web3;client|no-auth,http://localhost:{{execution_engine_port}}|http;ws|net;eth;subscribe;engine;web3;client"
  --EthStats.Enabled=false
  --Metrics.ExposePort={{execution_metrics_port}}
  --Metrics.Enabled=true
  --AuRaMerge.Enabled=true
  --Aura.TxPriorityContractAddress=0x4100000000000000000000000000000000000000
  --Aura.ForceSealing=true
  --Seq.MinLevel="Info"
  --Seq.ServerUrl="https://seq.nethermind.io/"
  --Seq.ApiKey="{{nethermind_seq_api_key}}"
  --Metrics.NodeName={{inventory_hostname}}
  --Metrics.PushGatewayUrl="{{nethermind_push_gateway_url}}"
  --Metrics.IntervalSeconds=5
  {% if (use_snap_sync is defined) and use_snap_sync %}
  --Sync.SnapSync=true
  --Sync.FastSync=false
  {% else %}
  --Sync.SnapSync=false
  --Sync.FastSync=true
  {% endif %}

# run as root, the nethermind image doesn't handle running regular user well
execution_user_id: "0:0"
