bootnode_container_name: bootnode
bootnode_memory: 2000m
bootnode_image_name: sigp/lighthouse:latest-unstable # protolambda/eth2-bootnode:cleanup

bootnode_volumes:
  - "{{home_dir}}/bootnode_data"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

bootnode_port: 9001

bootnode_ip: "{{ansible_host}}"

# 32 bytes, hex encoded, no 0x.
bootnode_p2p_priv_key: "0000"

bootnode_start_args: >
  lighthouse
  --debug-level="{{ beacon_log_level | lower }}"
  --datadir "/beacondata"
  --testnet-dir="/custom_config_data"
  beacon_node
  --disable-enr-auto-update
  --enr-address={{ansible_host}}
  --enr-tcp-port={{beacon_p2p_port}} --enr-udp-port={{beacon_p2p_port}}
  --port={{beacon_p2p_port}} --discovery-port={{beacon_p2p_port}}
  --eth1
  --http
  --http-address=0.0.0.0
  --http-port="{{beacon_api_port}}"
  --metrics
  --metrics-address=0.0.0.0
  --metrics-port="{{beacon_metrics_port}}"
  --listen-address=0.0.0.0
  --graffiti="{{graffiti}}"
  --target-peers={{hi_peer_count}}
  --http-allow-sync-stalled
  --merge
  --disable-packet-filter
  --execution-endpoints={{execution_endpoint}}
  --eth1-endpoints={{eth1endpoint}}
  --terminal-total-difficulty-override={{terminal_total_difficulty}}
  --suggested-fee-recipient={{fee_recipient}}
  --jwt-secrets="/jwtsecret"
