server:
  http_listen_port: "{{promtail_port}}"
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "{{loki_url}}"

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          instance: "{{inventory_hostname}}"
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          instance: "{{inventory_hostname}}"
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - labels:
          tag:
          stream:
