##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

# Gnosis: dapplion, alebanzas
# Gnosis devops: giacomolicari, riccardo-gnosis, davidalbela, gMonty030, Stavfilipps
# POA: igorbarinov
# Gateway: mandrigin, sibuser
github_user_pubkeys:
  - dapplion
  - giacomolicari
  - alebanzas
  - igorbarinov
  - parithosh
  - mandrigin
  - sibuser
  - riccardo-gnosis
  - davidalbela
  - gMonty030
  - Stavfilipps

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# eth1 endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551

eth1endpoint: http://127.0.0.1:8545

beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: chiado
chainID: 100100

# To allow using the deposit contract
eth2_genesis_eth1data_blockhash: "0x203e164cf3b6f6765abf2f0355a4d09e5eaf6a777243bc4407b569431cd95cb3"

# Projected for Aug 15th ~16h UTC (207360 blocks)
terminal_total_difficulty: "70560951604725799783765358597051456327101440"
fee_recipient: "0x88dFc82CF71fdeb23f82C33a202f6E2D19AC0541"
# enter bootnodes here if needed
bootnode_enrs: [
    # Local (old)
    "enr:-Ly4QBWdgA_Tt59pz3xeeMEIv9RXKjJn5pC4TiFxxmGcNrRAUTB5qVs6xTph7SLtLOPxlgn60mxaNyeAHc0inv1Zq40Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJ_LJMCJc2VjcDI1NmsxoQJW6aQs89Fzox8_YwwO1C-ubid5awCWhd8oUPP8s2VepYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    "enr:-Ly4QLtEwF2plyYK6wINg8p2cEvON5uxBRTGDjOVY-alCgBzfYoNqzAnYtMTRbH5iZgXAxAweh90i9FEtbN2OvhKZcMBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJ_LJ0qJc2VjcDI1NmsxoQLYBUr39uZ3zPfC9XK0f-g22J2Z8DF1Ax3e444dwUmy0ohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    "enr:-Ly4QHyiqcUzJ4CtI6bhSTAZAD92UMEKwKCObZ-9hSZJAfgtXkj4JbAbhK33rXhqLFeO3isINvpPy_TUvoLB71__rOEBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJ_fJsSJc2VjcDI1NmsxoQJjSw3xd3o7Rj1DzE7Wxlr6mEbt5s2re4ANlP_TMDLmUohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    "enr:-Ly4QN9Ro8-E9gyCCUuEYWlSwCbfzc2NkUGmN8YRDmg4K3rRP1FBiaDe9TWKVGaXhmb8F6qwYxW5h83hS6LjF8nJK34Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJ_fM6-Jc2VjcDI1NmsxoQNEtFv9oWxfpqPxFgpngTaWPHuGC6XEwaLdANypSZ-S2YhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    "enr:-Ly4QMpHRs1843yWgB5yA2epcTBo4BrGrEB6b2fPAfxryjEEFzIUc_FOJ3b7r6h0bD_Gg-gCrX_mUgZZM8D7Xfot9J8Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhLymbsOJc2VjcDI1NmsxoQKhmKRn59_w2tt_KNQ2Jhj-F3b9hxRkFYdtW3IGgXm0oIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    "enr:-Ly4QO80ytPwEEXF0B6Nsnk6N-89SI3Ja-wvhnMwTgvAiKCMNvOfHwf3FbJtLvZpP7O2v4ztnpqbdYEXngvLzgDsvSEBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhI5dgFeJc2VjcDI1NmsxoQMwMSfNp9AUZNAgWzYDo2nI1KNHej3aB2NWt8j9awAlO4hzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    "enr:-Ly4QAnBhPYD4_Cc3CyJhVqkLquWeGIY5xlKLhy9j_Bx845iNwSORtcXdLReWlK33PfqHTbqpsI-rm--egamtkrB7ywBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJO20mGJc2VjcDI1NmsxoQLhk56jmgLZTFopIhjoDlWpPiDjzLsrbnX7Z9iaOeg3PIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    "enr:-Ly4QNrYdrX4KY4tPgQKG3KcGySPE7QtpfFCGSujQUpQkErELFeDjuVWRzMxyyEQJTyVlTSPXxy4t9T2yrl4lBf5x8ABh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhI5dxlqJc2VjcDI1NmsxoQIzft6l-G1eo45O7v1eg0AZx4G-uwi4oGARFYQk1_vy5ohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    "enr:-Ly4QEGDwovw841Etzs5wJquRZFMGPNNcKh6rqa5_BCI64NKYKOFjWTPh0nbwDBR7caIqEoDMKWBFzTTmqFKIQzjPpsBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhI5dfvaJc2VjcDI1NmsxoQLTtR9MTMMQxDXWi7Gn3ABZD-NMyIaq1HxUtcDrjM7qz4hzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA",
    # From Igor (Gateway)
    "enr:-Ly4QKURsQNoND5tazZhAsKi4x1dxo4gWOktdpygSK6LfzT_D0b7jPWqcN5kCTUMnzwMEbH0N-ZK0dSJGy0dE62s2PUCh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhEEVxd6Jc2VjcDI1NmsxoQLLeV4mhW1Nsd2FpBXyj6JMsYQ8yYBSKTSUqNa-go0tlIhzeW5jbmV0cwCDdGNwgkpug3VkcIJKbg",
    "enr:-KG4QD8IsAMCVkRT73pLYm5Mh3o7Uk83Op4NPGi_qzy18xFJLYwA5cHrFaVw5apyu7Bc2xjhJHgfwXIrfG-SYCzZarEIhGV0aDKQ9f0tPAEAAG9aAAAAAAAAAIJpZIJ2NIJpcITJ7oKxiXNlY3AyNTZrMaECVZ5eL4ypBnJLN1jbP7PKFw0OruAF_dEx7zJDjSc28vODdGNwgkpvg3VkcIJKbw",
    "enr:-Ly4QIvbpjd7AcFjmY8Uj24uAZKAdRP3Hkur5no8K4bCTYZJMqVyEVS3UYmYJkLQnjWTS8FiL3fLTuk5Bx4BBCaAnkECh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhE-b1uSJc2VjcDI1NmsxoQKUkP2cx6GR9B6Kx9sf06TLRcwHy31ztU9bfjSJh7QpG4hzeW5jbmV0cwCDdGNwgkpug3VkcIJKbg",
    "enr:-Ly4QBpr_RcSPoXuHzcE6QbmPsM_ZRF8RVgNirwNgXumkroaRa3R0H33XtxDb4MgohVDAHmi3ocFCWR8gcJoZJD8I5MCh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhF9oXeCJc2VjcDI1NmsxoQPAW1a61k9_aCHpgOCNcLmi7mRFWZjXT2skaQb5_eLkHYhzeW5jbmV0cwCDdGNwgkpug3VkcIJKbg",
    "enr:-Ly4QOb7zmr8HUKayFJBSDJ2c2dM3-EhQDwSvYus27YoI7QDUxK9TTQCzcgING-i_h82bZOaxzrfZ3ft5ECP2dSVZLcCh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhK35IbCJc2VjcDI1NmsxoQOnaeYq_IE7LRiYCA2hyPqzePsGEToUKRyeAPyhLPr2oYhzeW5jbmV0cwCDdGNwgkpug3VkcIJKbg",
    "enr:-LK4QH5g33cHBTlnRsEegTWbgYvmK4PGIaND8x0C5wneDIirYeZY6Ej4DgnNoVmd7KsN7R_VpgBzJVEwuKAv5q8j4ikGh2F0dG5ldHOIAAIIIhEgAQaEZXRoMpDoY5pvAgAAb7QAAAAAAAAAgmlkgnY0gmlwhFmFZSGJc2VjcDI1NmsxoQJktmZm0Ex8MpliguydcMakW0K_H2NeRbG5Mi5rTDg3nYN0Y3CCSm-DdWRwgkpv",
  ]

eth1_bootnode_enode:
  [
    "enode://6a675f365058f272925a5c04636df770f30686999449ef66a8e1da03cf5d4a6d6dc0a28db8c95393200dcdffa4a8a3acb9f2cac392134cef04113faa9023584b@68.183.83.184:30303",
    "enode://38e547f4f58940fa4fe20ee56191a9ed013930d3506e58dece45e76e4c706baf422561d6b9adb300633321b878b3c4f18d07a724b72693e0609937d00559350a@159.203.36.192:30303",
    "enode://883cf9b2310f185f7911eceb84398c502b8a7df291b641e8ad368d40cee29e590be583e93f0a9cde7edd5d5982505b46090ab1f590f5ef8d22cc8592cd373a1d@159.203.39.74:30303",
    "enode://c4146451d36256c5f15e38de594cb9b24be380f9c2274fe6940a79f0e95a73b913bf3b0b788aa25abd9cb71c17eb3324e0e0d6c0c8fb94cdfd16be2ab6dc31f3@159.223.38.196:30303",
    "enode://d4cff3f5b7963a9584aabf213a07d683e955f0a60db300da9c6c9e12380405b1a7b0900bcce9092f3680474ddf0f13e50e64f8759b0b20c2a9b3582a592a677c@159.223.51.175:30303",
    "enode://d7acbcbb1ad70a8ea8737401ceb1a5f56917242c3bbc48024c7057e8b7f8d7b57b70eea3373312ea46d79ea967ddf3e46808f3f022ad61e3bb0721d7be733ed0@188.166.110.195:30303",
    "enode://2844b41ee38a468398d43c02fe91ef4838ae8ec9975a51a0e599e83155c468f4c3da1c4313521f4ad5ce59a179d46c5314196c6bbff54cad17e54df9fa31803c@142.93.128.87:30303",
    "enode://b890f54e75c1caefe1ecd8f1dfe6f90c6cc48d62ad098ae7a9da6753841d7bf3b703f9fb229f7dd490fa6d2e8dcab56cb0a59076b0e390e50cc8146b86d03ef1@147.182.210.97:30303",
    "enode://a2348ab2374237e6c28fd55c1fd46afb492d72ae00b8cb1f46c5b38687184489d26a119aacb6736088e4f44010898a1668906967d2676b97612e963ecc73fa5a@142.93.198.90:30303",
    "enode://97f33b441d65db48e4f853efd206ed4a5e5571acb0a34998a69e2d367206fd462708411ff6ca1870555bb65fea1aa7f7f6dfbca6ab4c2b7406f2009cfc8459f7@142.93.126.246:30303",
  ]

mining_addresses:
  - "0xaaa0611623f27b169557d178da5d9cd3e1044ce1"
  - "0xaaa939c83aa32af422ba0da4a44888c04af65325"
  - "0xaaa5807408ad28bdbceb2911a6eb9541e880505d"
  - "0xaaa79fbce01f2ad7cc8424e7a8361bdec0c662c8"
  - "0xaaa6946c6ec277335cb3ef93bc140489c1b412b4"
  - "0xaaa732a914b4780e33bcac7f129120a6ceb7ea0e"
  - "0xaaa0edbec2091470d5a8d8876bf5cf681b0d6468"
  - "0xaaad85d426c0efeb2ee215d6dd4c6ccc39bb9106"
  - "0xaaaafb931bf8ebe4af36dca978b94c0efbd300d6"
  - "0xaaa49c8aeca0afd329012522563b28c75d687ac2"

keystores_password: "{{denver_keystores_password}}"

# Genesis. chiado_mnemonics is stored in `denver/inventory/group_vars/secrets.yaml`
genesis_mnemonics: "{{chiado_mnemonics}}"
mnemonic_0: "{{chiado_mnemonics[0].mnemonic}}"
mnemonic_1: "{{chiado_mnemonics[1].mnemonic}}"
mnemonic_2: "{{chiado_mnemonics[2].mnemonic}}"
mnemonic_3: "{{chiado_mnemonics[3].mnemonic}}"
mnemonic_4: "{{chiado_mnemonics[4].mnemonic}}"
mnemonic_5: "{{chiado_mnemonics[5].mnemonic}}"
mnemonic_6: "{{chiado_mnemonics[6].mnemonic}}"
mnemonic_7: "{{chiado_mnemonics[7].mnemonic}}"
mnemonic_8: "{{chiado_mnemonics[8].mnemonic}}"
mnemonic_9: "{{chiado_mnemonics[9].mnemonic}}"
mnemonic_10: "{{chiado_mnemonics[10].mnemonic}}"
mnemonic_11: "{{chiado_mnemonics[11].mnemonic}}"
mnemonic_12: "{{chiado_mnemonics[12].mnemonic}}"
mnemonic_13: "{{chiado_mnemonics[13].mnemonic}}"
mnemonic_14: "{{chiado_mnemonics[14].mnemonic}}"
mnemonic_15: "{{chiado_mnemonics[15].mnemonic}}"

# Note: 0 is correct, but due to an underflow bug (being fixed), doesn't work.
eth1_deposit_contract_first_block: 1
# Block from which to start indexing. Set to a higher value for shadow-forks
explorer_execution_first_block: 1

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"

prometheus_remote_write_configs:
  # NOTE: For some reason DO hosts can't resolve themerge-monitoring.gnosischainscan.com domain
  - url: https://themerge-monitoring.gnosischainscan.com/prometheus/api/v1/write/
    username: themergeprometheusremotewrite
    password: "{{themergemonitoring_remote_write_password}}"
  - url: https://hostedmetrics.com/s/cQ4UMmFc/prometheus/remote/write/
    username: cQ4UMmFc
    password: "{{hostedmetrics_remote_write_password}}"

prometheus_enabled: true
remote_write_auth: true
cadvisor_enabled: true
promtail_enabled: true
promtail_loki_server_url: "https://136217:{{loki_pusher_api_key}}@logs-prod-us-central1.grafana.net/loki/api/v1/push"
eth2_validator_metrics_enabled: true
eth_metrics_exporter_enabled: true
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: samcm/ethereum-metrics-exporter:0.11.0

no_validator_keys: false
ethstats_host: "ethstats.chiado.gnosischain.com"
ethstats_nethermind_enabled: true
ethstats_besu_enabled: false
ethstats_erigon_enabled: false
ethstats_geth_enabled: false

# Skip "propagate official prometheus and promtool binaries" step.
# It freezes forever and when it works it's extremely slow.
# Binaries are downloaded from Github to the ansible controller host, them uploaded from there.
prometheus_skip_install: true
prometheus_binary_url: https://d1zrfxp177ra46.cloudfront.net/prometheus-2.37.0.linux-amd64

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
eth1_engine_port_no_auth: 8550
eth1_engine_port: 8551
eth1_engine_snoop_port: 8560
eth1_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"
prometheus_web_listen_address: "0.0.0.0:9090"
eth1_metrics_port: 8002
eth_metrics_exporter_port: 8003
cadvisor_port: 9280
promtail_port: 9080
explorer_execution_public_port: 3334
explorer_beacon_public_port: 3333
public_ethstats: 3000

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}-{{eth1_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
local_eth2_config_filepath: "{{local_custom_config_data_host_dir}}/config.yaml"
local_eth1_genesis_filepath: "{{local_custom_config_data_host_dir}}/nethermind_genesis.json"
local_mnemonics_filepath: "{{local_custom_config_data_host_dir}}/mnemonics.yaml"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{inventory_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{inventory_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ansible_user}}"
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
execution_node_dir: "{{home_dir}}/execution"
keystore_password_filename: "keystores_password.txt"

##############################################
# common log config
##############################################
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443
  - 8080
  - "{{eth1_rpc_port}}"
  - "{{eth1_metrics_port}}"
  - "{{explorer_execution_public_port}}"
  - "{{explorer_beacon_public_port}}"
  - "{{public_ethstats}}"

firewall_allowed_udp_ports:
  - 30303
  - 9000
