##############################################
# image name and image location
##############################################
eth2_client_name: lodestar

# TODO: switch to merge f2f, but mainnet preset
beacon_image_name: chainsafe/lodestar:next
validator_image_name: chainsafe/lodestar:next
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

eth2_github_external_user_pubkeys:
  - dapplion
  - wemeetagain
  - tuyennhv
  - g11tech
  - dadepo
  - philknows

beacon_env:
  LODESTAR_PRESET: mainnet

validator_env:
  LODESTAR_PRESET: mainnet

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  - "{{testnet_dir}}:/custom_config_data"
##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  beacon
  --preset=gnosis
  --network=gnosis
  --dataDir=/beacondata
  --paramsFile=/custom_config_data/config.yaml
  --genesisStateFile=/custom_config_data/genesis.ssz
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  {% for bootnode_enr in bootnode_enrs %}
  --bootnodes="{{bootnode_enr}}"
  {% endfor %}
  {% endif %}
  --network.connectToDiscv5Bootnodes
  --discv5
  --eth1
  --jwt-secret="/jwtsecret"
  --execution.urls={{execution_endpoint}}
  --eth1.providerUrls={{eth1endpoint}}
  --eth1.depositContractDeployBlock={{execution_deposit_contract_first_block}}
  --enr.ip={{ansible_host}}
  --rest
  --rest.port={{beacon_api_port}}
  --rest.address=0.0.0.0
  --rest.namespace="*"
  --logLevel={{beacon_log_level | lower}}
  --logFile=/beacondata/beacon.log
  --logFileLevel=debug
  --logFileDailyRotate=5
  --metrics
  --metrics.port={{beacon_metrics_port}}

validator_start_args: >
  validator
  --preset=gnosis
  --network=gnosis
  --dataDir=/validatordata
  --paramsFile=/custom_config_data/config.yaml
  --keystoresDir=/validatordata/keystores
  --secretsDir=/validatordata/secrets/
  --server={{beacon_endpoint}}
  --logFile=/validatordata/validator.log
  --logFileLevel=debug
  --logFileDailyRotate=5
  --graffiti={{graffiti}}

##############################################
# memory limits
##############################################
validator_memory: 2000M
validator_kernel_memory: 2500M
beacon_memory: 7000M
beacon_kernel_memory: 7500M

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"

separate_validator_process_enabled: true
