# Setup hosts from scatch
- import_playbook: ../../tasks/setup_machine.yml
- import_playbook: ../../tasks/start_firewall.yml

- name: Setup Google DNS resolver
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: set resolver
      shell: |
        if ! grep -q '^nameserver 8.8.8.8$' /etc/resolv.conf; then
            echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
        fi
        if ! grep -q '^nameserver 8.8.4.4$' /etc/resolv.conf; then
            echo 'nameserver 8.8.4.4' >> /etc/resolv.conf
        fi

- import_playbook: ../../tasks/metrics/setup_node_metrics.yml
- import_playbook: ../../tasks/setup_node_exporter_and_prometheus.yml
- import_playbook: ../../setup_logging_capability.yml
# - hosts: all
#   gather_facts: false
#   tasks:
#     - name: Set ansible_ssh_user to root
#       set_fact:
#         ansible_ssh_user: "{{initial_remote_user}}"
#       changed_when: false
#       delegate_to: localhost
#       run_once: true
# After this playbook: whoami -> root

# - import_playbook: ../tasks/create_bootstrap_user.yml
#
# - hosts: all
#   gather_facts: false
#   tasks:
#     - name: Set ansible_ssh_user to bootstrap_user
#       set_fact:
#         ansible_ssh_user: "{{bootstrap_user}}"
#       changed_when: false
#       delegate_to: localhost
#       run_once: true
