--- 
- name: Place metrics pusher cron job
  hosts: hetzner
  gather_facts: false
  serial: 20
  tasks: 
    - name: Creates a cron job for pushing node metrics 
      ansible.builtin.cron:
        name: node_machine_metrics_pusher
        weekday: "*"
        minute: "*/10"
        hour: "*"
        user: root
        job: "curl http://localhost:9100/metrics | curl -u prometheus:neboWcmRwkbuk60y --data-binary @- https://themerge-monitoring.gnosischainscan.com/pushgateway/metrics/job/node_metrics/instance/gbc-merge"
        cron_file: node_machine_metrics_pusher

    - name: Creates a cron job for pushing cadvisor container metrics 
      ansible.builtin.cron:
        name: cadvisor_machine_metrics_pusher
        weekday: "*"
        minute: "*/10"
        hour: "*"
        user: root
        job: "curl http://localhost:8085/metrics | curl -u prometheus:neboWcmRwkbuk60y --data-binary @- https://themerge-monitoring.gnosischainscan.com/pushgateway/metrics/job/cadvisor_metrics/instance/gbc-merge-cadvisor"
        cron_file: cadvisor_machine_metrics_pusher
  