- hosts: all
  gather_facts: false
  tasks:
    - name: Set ansible_ssh_user to root
      set_fact:
        ansible_ssh_user: "{{initial_remote_user}}"
      changed_when: false
      delegate_to: localhost
      run_once: true
# After this playbook: whoami -> root

- import_playbook: tasks/create_bootstrap_user.yml

- hosts: all
  gather_facts: false
  tasks:
    - name: Set ansible_ssh_user to bootstrap_user
      set_fact:
        ansible_ssh_user: "{{bootstrap_user}}"
      changed_when: false
      delegate_to: localhost
      run_once: true
# After this playbook: whoami -> devops

# Setup hosts from scatch
- import_playbook: tasks/setup_machine.yml
- import_playbook: tasks/start_firewall.yml

# Generate eth2 genesis + keys on remote host
- import_playbook: tasks/generate_eth2_genesis_and_keys.yml
# Upload custom config data
- import_playbook: tasks/upload_custom_config_data.yml

# Run all containers
- import_playbook: setup_execution_and_consensus_full.yml
- import_playbook: tasks/start_txfuzz.yml
- import_playbook: tasks/setup_test_sync_cron.yml
- import_playbook: setup_beacon_and_execution_explorer_full.yml
#
# TODO:
# - Update bootnodes and restart containers
