# Setup hosts from scatch
- import_playbook: tasks/create_bootstrap_user_and_provision_machine.yml
- import_playbook: tasks/start_firewall.yml
- import_playbook: tasks/setup_machine.yml

# Generate eth2 genesis + keys on remote host
- import_playbook: tasks/generate_eth2_genesis_and_keys.yml
# Upload custom config data
- import_playbook: tasks/upload_custom_config_data.yml

# Run all containers
- import_playbook: setup_execution_and_consensus_full.yml
- import_playbook: setup_node_exporter_and_prometheus.yml
#
# TODO:
# - Update bootnodes and restart containers
