# Upload custom config data
- import_playbook: tasks/start_txfuzz.yml
- import_playbook: tasks/setup_test_sync_cron.yml
- import_playbook: setup_beacon_and_execution_explorer_full.yml
#
# TODO:
# - Update bootnodes and restart containers
