- name: Upload faucet data
  hosts: faucet
  gather_facts: true
  tasks:
    - name: Creates faucet dir
      file:
        path: "{{faucet_node_dir}}"
        state: directory
    - name: Move the faucet config j2 template to remote
      template:
        src: faucet/chains.json.j2
        dest:  "{{faucet_node_dir}}/chains.json"
        mode: '755'
    - name: Move the faucet faucet.properties j2 template to remote
      template:
        src: faucet/fauceth.properties.j2
        dest: "{{faucet_node_dir}}/fauceth.properties"
        mode: '755'
- name: Start faucet
  hosts: faucet
  gather_facts: true
  serial: 20
  tasks:
    - name: Start faucet
      docker_container:
        name: "{{ faucet_container_name }}"
        state: started
        image: "{{ faucet_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: bridge
        ports:
          - "{{ faucet_port }}:8000"
        restart: "{{ explorer_require_restart | default(false) }}"
        volumes: "{{ faucet_volumes }}"
        env:
          HCAPTCHA_SITEKEY: "{{ hcaptcha_site_key }}"
          HCAPTCHA_SECRET: "{{ hcaptcha_secret }}"