---
- name: Start beacon node
  hosts: beacon
  gather_facts: false
  tasks:
    - name: Stop beacon node container
      when: wipe | default(false)
      community.docker.docker_container:
        name: "{{ beacon_container_name }}"
        state: absent
    # - name: Delete beacon node datadir
    #   when: wipe | default(false)
    #   file:
    #     path: "{{ beacon_node_dir }}"
    #     state: absent
    - name: Creates beacon data dir
      file:
        path: "{{beacon_node_dir}}"
        state: directory
    - name: Modify permissions to match user-group inside docker image
      file:
        path: "{{beacon_node_dir}}"
        group: "{{beacon_user_id.split(':')[0]}}"
        owner: "{{beacon_user_id.split(':')[1]}}"
        recurse: true
      become: true
    - name: Start beacon node container
      community.docker.docker_container:
        name: "{{ beacon_container_name }}"
        state: started
        image: "{{ beacon_image_name }}"
        pull: true
        stop_timeout: 90
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ beacon_require_restart | default(false) }}"
        volumes: "{{ beacon_volumes }}"
        command: "{{ beacon_start_args }}"
        log_options: "{{ loki_log_options }}"
        log_driver: "{{ loki_log_driver }}"
        env: "{{ beacon_env | default({}) }}"
        user: "{{beacon_user_id}}"
