- name: Upload network data
  hosts: beacon, validator, execution
  gather_facts: true
  tasks:
    - name: Create custom_config_data folder
      file:
        path: "{{testnet_dir}}"
        state: directory
    - name: Copy custom_config_data
      copy:
        src: "{{local_custom_config_data_host_dir}}/"
        dest: "{{testnet_dir}}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy keystore password
      when:
        - keystore_password_filename is defined
        - mining_keyi is defined
      become: true
      copy:
        dest: "{{testnet_dir}}/{{keystore_password_filename}}"
        content: "{{keystores_password}}"

    - name: Copy deploy_block.txt
      become: true
      copy:
        dest: "{{testnet_dir}}/deploy_block.txt"
        content: "{{explorer_execution_first_block}}"

    - name: Create Keystores folder
      when: mining_keyi is defined
      file:
        path: "{{execution_miner_keystore_dir}}"
        state: directory

    - name: Copy Keystore file
      when: mining_keyi is defined
      copy:
        src: "{{inventory_dir}}/../keystores/{{miner_keystore_filename[mining_keyi]}}"
        dest: "{{execution_miner_keystore_dir}}/{{miner_keystore_filename[mining_keyi]}}"

    - name: Add write permissions to Miner Keystores
      when: execution_keystore_attr is defined
      file:
        path: "{{execution_miner_keystore_dir}}"
        attributes: "{{execution_keystore_attr}}"
        recurse: true

    - name: Modify permissions to match user-group inside docker image
      file:
        path: "{{testnet_dir}}"
        group: "777"
        recurse: true
      become: true

- name: Init JWT secret
  hosts: [beacon, execution]
  gather_facts: false
  tasks:
    - name: Stat JWT path
      register: jwt_path_stat
      stat:
        path: "{{ home_dir }}/jwtsecret"
    - name: Creates JWT secret
      when: not jwt_path_stat.stat.exists
      shell: echo -n 0x$(openssl rand -hex 32 | tr -d "\n") > "{{ home_dir }}/jwtsecret"
